### ISSUE TITLE
trying to add blob container URL crashes (user reported)

### ISSUE THREAD

**Issue by praneetloke** [praneetloke/AzureStorageExplorerAndroid#14]
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
	at android.support.v4.app.DialogFragment.dismissInternal(Unknown Source)
	at android.support.v4.app.DialogFragment.dismiss(Unknown Source)
	at com.pl.azurestorageexplorer.MainActivity$5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by praneetloke** [comment]
I can't reproduce this issue anymore.
